name: Cypress Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Cache Node modules
      - name: Cache Node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Step 3: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Create placeholder directories for screenshots and videos
      - name: Create placeholder directories
        run: |
          mkdir -p cypress/screenshots
          mkdir -p cypress/videos

      # Step 6: Start application server
      - name: Start application server
        run: npm run start &
        env:
          CI: true

      # Step 7: Wait for server to be ready
      - name: Wait for server to be ready
        run: |
          for i in $(seq 1 60); do
            curl --silent http://localhost:3000 && break
            echo "Waiting for server..."
            sleep 1
          done

      # Step 8: Run Cypress tests
      - name: Run Cypress tests
        run: npm run cypress:run

      # Step: List screenshots to verify
      - name: List screenshot files
        run: ls -l cypress/screenshots

      # Step 9: Generate the HTML report
      - name: Generate HTML report
        run: npm run report:generate

      # Step 10: List report files after generation
      - name: List report files after generation
        run: ls -l cypress/reports

      # Step 11: Upload Cypress screenshots as an artifact
      - name: Upload Cypress screenshots
        if: always()  # Upload screenshots even if the test fails
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: warn

      # Step 12: Upload Cypress videos as an artifact
      - name: Upload Cypress videos
        if: always()  # Upload videos even if the test fails
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos  # Ensure this path is provided
          if-no-files-found: warn

      # Step 13: Upload the HTML report as an artifact
      - name: Upload Cypress Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report
          path: cypress/reports/mochawesome.html
